"""Recovery workflow events."""

from __future__ import annotations

from enum import Enum


class RecoveryEvent(str, Enum):
    ANALYSIS_REQUESTED = "ANALYSIS_REQUESTED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    ANALYSIS_TERMINAL_FAILURE = "ANALYSIS_TERMINAL_FAILURE"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    ACTION_SCHEDULED = "ACTION_SCHEDULED"
    AUTO_EXECUTE = "AUTO_EXECUTE"
    STOP_SELECTED = "STOP_SELECTED"
    APPROVED_NOW = "APPROVED_NOW"
    APPROVED_LATER = "APPROVED_LATER"
    APPROVAL_REJECTED_REANALYZE = "APPROVAL_REJECTED_REANALYZE"
    APPROVAL_REJECTED_STOP = "APPROVAL_REJECTED_STOP"
    REEVALUATION_DUE = "REEVALUATION_DUE"
    ACTION_DUE = "ACTION_DUE"
    PAYMENT_VERIFIED = "PAYMENT_VERIFIED"
    SCHEDULE_CANCELLED = "SCHEDULE_CANCELLED"
    ACTION_ACCEPTED_OR_UNKNOWN = "ACTION_ACCEPTED_OR_UNKNOWN"
    ACTION_FAILED_REANALYZE = "ACTION_FAILED_REANALYZE"
    TERMINAL_ACTION_FAILURE = "TERMINAL_ACTION_FAILURE"
    NEGATIVE_OUTCOME_OR_TIMEOUT = "NEGATIVE_OUTCOME_OR_TIMEOUT"
    RECOVERY_EXHAUSTED = "RECOVERY_EXHAUSTED"
    STOPPING_RULE_MET = "STOPPING_RULE_MET"
