"""Audit timeline read services with privacy-safe evidence projection."""

from __future__ import annotations

from uuid import UUID

from sqlalchemy.orm import Session

from app.core.errors import ForbiddenError, NotFoundError
from app.repositories.audit_log_repo import AuditLogRepository
from app.repositories.recovery_case_repo import RecoveryCaseRepository
from app.schemas.timeline import TimelineEntry, TimelineResponse
from app.services.timeline_evidence import project_timeline_evidence


class TimelineService:
    def __init__(self, session: Session) -> None:
        self._case_repo = RecoveryCaseRepository(session)
        self._audit_repo = AuditLogRepository(session)

    def get_case_timeline(
        self,
        organization_id: UUID,
        case_id: UUID,
    ) -> TimelineResponse:
        if self._case_repo.exists_in_other_organization(case_id, organization_id):
            raise ForbiddenError(
                code="TENANT_ACCESS_DENIED",
                message="Recovery case belongs to another organization.",
            )

        if not self._case_repo.exists_for_organization(case_id, organization_id):
            raise NotFoundError(
                code="CASE_NOT_FOUND",
                message="Recovery case was not found.",
            )

        # Ordering is the repository's responsibility and is canonical:
        # created_at ASC, then id ASC. It is not re-sorted here.
        entries = self._audit_repo.list_for_case(case_id, organization_id)
        return TimelineResponse(
            items=[
                TimelineEntry(
                    id=entry.id,
                    occurred_at=entry.created_at,
                    event_type=entry.event_type,
                    actor_type=entry.actor_type,
                    # `summary` is generated by the backend from closed enum
                    # values and fixed operator-facing strings; it never
                    # interpolates operator text, provider payloads or model
                    # output. See PROMPT_22_SECURITY_REPORT section 6.
                    summary=entry.summary,
                    evidence=project_timeline_evidence(entry.evidence),
                )
                for entry in entries
            ]
        )
